### ISSUE TITLE
GenerateAssemblyInfo property should be included in msbuild command

### ISSUE THREAD

**Issue by Iamcerba** [Lexcess/SemanticVersioning.MSBuild#1]
First of all I would like to say thank you for your package.

I think it worth mentioning that in my case "ApplySemanticVersion" target hadn't executed unless I added additional property overload ("GenerateAssemblyInfo") in msbuild command:

```csharp
msbuild.exe /t:Build /p:SemanticVersion=1.2.3;Tag=-rc1;GenerateAssemblyInfo=False <project filename>.csproj
```

Also could you please include msbuild command examples into README.md, it will be usefull?

**Comment by Lexcess** [comment]
Hi @Iamcerba thanks for the comment. Yes that was a compromise in the new version of the package due to the changes in assemblyinfo generation in the VS 2017 project formats. It is a good catch and I'll update the docs. Thanks again for raising it!
